/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlayerRouteImport } from './routes/player'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as FavoriteRouteImport } from './routes/favorite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PodcastIdRouteImport } from './routes/podcast.$id'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as OauthCallbackRouteImport } from './routes/oauth/callback'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AudiobookIdRouteImport } from './routes/audiobook.$id'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as AlbumIdRouteImport } from './routes/album.$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTracksRouteImport } from './routes/admin/tracks'
import { Route as AdminSignupRouteImport } from './routes/admin/signup'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminResetPasswordRouteImport } from './routes/admin/reset-password'
import { Route as AdminPodcastsRouteImport } from './routes/admin/podcasts'
import { Route as AdminPlaylistsRouteImport } from './routes/admin/playlists'
import { Route as AdminMoodsRouteImport } from './routes/admin/moods'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGenresRouteImport } from './routes/admin/genres'
import { Route as AdminForgotPasswordRouteImport } from './routes/admin/forgot-password'
import { Route as AdminAuthorsRouteImport } from './routes/admin/authors'
import { Route as AdminAudiobooksRouteImport } from './routes/admin/audiobooks'
import { Route as AdminAlbumsRouteImport } from './routes/admin/albums'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerRoute = PlayerRouteImport.update({
  id: '/player',
  path: '/player',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoriteRoute = FavoriteRouteImport.update({
  id: '/favorite',
  path: '/favorite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastIdRoute = PodcastIdRouteImport.update({
  id: '/podcast/$id',
  path: '/podcast/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiobookIdRoute = AudiobookIdRouteImport.update({
  id: '/audiobook/$id',
  path: '/audiobook/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTracksRoute = AdminTracksRouteImport.update({
  id: '/admin/tracks',
  path: '/admin/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignupRoute = AdminSignupRouteImport.update({
  id: '/admin/signup',
  path: '/admin/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResetPasswordRoute = AdminResetPasswordRouteImport.update({
  id: '/admin/reset-password',
  path: '/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPodcastsRoute = AdminPodcastsRouteImport.update({
  id: '/admin/podcasts',
  path: '/admin/podcasts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlaylistsRoute = AdminPlaylistsRouteImport.update({
  id: '/admin/playlists',
  path: '/admin/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMoodsRoute = AdminMoodsRouteImport.update({
  id: '/admin/moods',
  path: '/admin/moods',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGenresRoute = AdminGenresRouteImport.update({
  id: '/admin/genres',
  path: '/admin/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminForgotPasswordRoute = AdminForgotPasswordRouteImport.update({
  id: '/admin/forgot-password',
  path: '/admin/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthorsRoute = AdminAuthorsRouteImport.update({
  id: '/admin/authors',
  path: '/admin/authors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAudiobooksRoute = AdminAudiobooksRouteImport.update({
  id: '/admin/audiobooks',
  path: '/admin/audiobooks',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlbumsRoute = AdminAlbumsRouteImport.update({
  id: '/admin/albums',
  path: '/admin/albums',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorite': typeof FavoriteRoute
  '/library': typeof LibraryRoute
  '/notifications': typeof NotificationsRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/albums': typeof AdminAlbumsRoute
  '/admin/audiobooks': typeof AdminAudiobooksRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moods': typeof AdminMoodsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/audiobook/$id': typeof AudiobookIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorite': typeof FavoriteRoute
  '/library': typeof LibraryRoute
  '/notifications': typeof NotificationsRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/albums': typeof AdminAlbumsRoute
  '/admin/audiobooks': typeof AdminAudiobooksRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moods': typeof AdminMoodsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/audiobook/$id': typeof AudiobookIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorite': typeof FavoriteRoute
  '/library': typeof LibraryRoute
  '/notifications': typeof NotificationsRoute
  '/player': typeof PlayerRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/admin/albums': typeof AdminAlbumsRoute
  '/admin/audiobooks': typeof AdminAudiobooksRoute
  '/admin/authors': typeof AdminAuthorsRoute
  '/admin/forgot-password': typeof AdminForgotPasswordRoute
  '/admin/genres': typeof AdminGenresRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moods': typeof AdminMoodsRoute
  '/admin/playlists': typeof AdminPlaylistsRoute
  '/admin/podcasts': typeof AdminPodcastsRoute
  '/admin/reset-password': typeof AdminResetPasswordRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/signup': typeof AdminSignupRoute
  '/admin/tracks': typeof AdminTracksRoute
  '/admin/users': typeof AdminUsersRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/audiobook/$id': typeof AudiobookIdRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/podcast/$id': typeof PodcastIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorite'
    | '/library'
    | '/notifications'
    | '/player'
    | '/profile'
    | '/search'
    | '/settings'
    | '/admin/albums'
    | '/admin/audiobooks'
    | '/admin/authors'
    | '/admin/forgot-password'
    | '/admin/genres'
    | '/admin/login'
    | '/admin/moods'
    | '/admin/playlists'
    | '/admin/podcasts'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/signup'
    | '/admin/tracks'
    | '/admin/users'
    | '/album/$id'
    | '/artist/$id'
    | '/audiobook/$id'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/oauth/callback'
    | '/playlist/$id'
    | '/podcast/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorite'
    | '/library'
    | '/notifications'
    | '/player'
    | '/profile'
    | '/search'
    | '/settings'
    | '/admin/albums'
    | '/admin/audiobooks'
    | '/admin/authors'
    | '/admin/forgot-password'
    | '/admin/genres'
    | '/admin/login'
    | '/admin/moods'
    | '/admin/playlists'
    | '/admin/podcasts'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/signup'
    | '/admin/tracks'
    | '/admin/users'
    | '/album/$id'
    | '/artist/$id'
    | '/audiobook/$id'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/oauth/callback'
    | '/playlist/$id'
    | '/podcast/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/favorite'
    | '/library'
    | '/notifications'
    | '/player'
    | '/profile'
    | '/search'
    | '/settings'
    | '/admin/albums'
    | '/admin/audiobooks'
    | '/admin/authors'
    | '/admin/forgot-password'
    | '/admin/genres'
    | '/admin/login'
    | '/admin/moods'
    | '/admin/playlists'
    | '/admin/podcasts'
    | '/admin/reset-password'
    | '/admin/settings'
    | '/admin/signup'
    | '/admin/tracks'
    | '/admin/users'
    | '/album/$id'
    | '/artist/$id'
    | '/audiobook/$id'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/oauth/callback'
    | '/playlist/$id'
    | '/podcast/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoriteRoute: typeof FavoriteRoute
  LibraryRoute: typeof LibraryRoute
  NotificationsRoute: typeof NotificationsRoute
  PlayerRoute: typeof PlayerRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AdminAlbumsRoute: typeof AdminAlbumsRoute
  AdminAudiobooksRoute: typeof AdminAudiobooksRoute
  AdminAuthorsRoute: typeof AdminAuthorsRoute
  AdminForgotPasswordRoute: typeof AdminForgotPasswordRoute
  AdminGenresRoute: typeof AdminGenresRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMoodsRoute: typeof AdminMoodsRoute
  AdminPlaylistsRoute: typeof AdminPlaylistsRoute
  AdminPodcastsRoute: typeof AdminPodcastsRoute
  AdminResetPasswordRoute: typeof AdminResetPasswordRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSignupRoute: typeof AdminSignupRoute
  AdminTracksRoute: typeof AdminTracksRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistIdRoute: typeof ArtistIdRoute
  AudiobookIdRoute: typeof AudiobookIdRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  PodcastIdRoute: typeof PodcastIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player': {
      id: '/player'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof PlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorite': {
      id: '/favorite'
      path: '/favorite'
      fullPath: '/favorite'
      preLoaderRoute: typeof FavoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast/$id': {
      id: '/podcast/$id'
      path: '/podcast/$id'
      fullPath: '/podcast/$id'
      preLoaderRoute: typeof PodcastIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiobook/$id': {
      id: '/audiobook/$id'
      path: '/audiobook/$id'
      fullPath: '/audiobook/$id'
      preLoaderRoute: typeof AudiobookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tracks': {
      id: '/admin/tracks'
      path: '/admin/tracks'
      fullPath: '/admin/tracks'
      preLoaderRoute: typeof AdminTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signup': {
      id: '/admin/signup'
      path: '/admin/signup'
      fullPath: '/admin/signup'
      preLoaderRoute: typeof AdminSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reset-password': {
      id: '/admin/reset-password'
      path: '/admin/reset-password'
      fullPath: '/admin/reset-password'
      preLoaderRoute: typeof AdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/podcasts': {
      id: '/admin/podcasts'
      path: '/admin/podcasts'
      fullPath: '/admin/podcasts'
      preLoaderRoute: typeof AdminPodcastsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/playlists': {
      id: '/admin/playlists'
      path: '/admin/playlists'
      fullPath: '/admin/playlists'
      preLoaderRoute: typeof AdminPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moods': {
      id: '/admin/moods'
      path: '/admin/moods'
      fullPath: '/admin/moods'
      preLoaderRoute: typeof AdminMoodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/genres': {
      id: '/admin/genres'
      path: '/admin/genres'
      fullPath: '/admin/genres'
      preLoaderRoute: typeof AdminGenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/forgot-password': {
      id: '/admin/forgot-password'
      path: '/admin/forgot-password'
      fullPath: '/admin/forgot-password'
      preLoaderRoute: typeof AdminForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/authors': {
      id: '/admin/authors'
      path: '/admin/authors'
      fullPath: '/admin/authors'
      preLoaderRoute: typeof AdminAuthorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audiobooks': {
      id: '/admin/audiobooks'
      path: '/admin/audiobooks'
      fullPath: '/admin/audiobooks'
      preLoaderRoute: typeof AdminAudiobooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/albums': {
      id: '/admin/albums'
      path: '/admin/albums'
      fullPath: '/admin/albums'
      preLoaderRoute: typeof AdminAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoriteRoute: FavoriteRoute,
  LibraryRoute: LibraryRoute,
  NotificationsRoute: NotificationsRoute,
  PlayerRoute: PlayerRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AdminAlbumsRoute: AdminAlbumsRoute,
  AdminAudiobooksRoute: AdminAudiobooksRoute,
  AdminAuthorsRoute: AdminAuthorsRoute,
  AdminForgotPasswordRoute: AdminForgotPasswordRoute,
  AdminGenresRoute: AdminGenresRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMoodsRoute: AdminMoodsRoute,
  AdminPlaylistsRoute: AdminPlaylistsRoute,
  AdminPodcastsRoute: AdminPodcastsRoute,
  AdminResetPasswordRoute: AdminResetPasswordRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSignupRoute: AdminSignupRoute,
  AdminTracksRoute: AdminTracksRoute,
  AdminUsersRoute: AdminUsersRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistIdRoute: ArtistIdRoute,
  AudiobookIdRoute: AudiobookIdRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  PodcastIdRoute: PodcastIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
